const ROLES = {
    GUEST: {id: 0, title: 'Гость'},
    MANAGER: {id: 3, title: 'Менеджер'},
    DIRECTOR: {id: 15, title: 'Руководитель'},
    ADMIN: {id: 31, title: 'Администратор'},
}

const CLASSES = {
    STREETSIGN: 3,
    CLR_STREETSIGN: 9,
}

const STREETSIGN_COLORS = [
    { id: 0,  title: 'Синий',              rgb: '#283474', bg_rgb: null,      ORACAL: '049',     RAL: '5002'},
    { id: 1,  title: 'Ультрамариновый',    rgb: '#21419A', bg_rgb: null,      ORACAL: '086',     RAL: '5005'},
    { id: 2,  title: 'Голубой',            rgb: '#0E5FAD', bg_rgb: null,      ORACAL: '052',     RAL: '5015'},
    { id: 3,  title: 'Темно-зеленый',      rgb: '#013C24', bg_rgb: null,      ORACAL: '060',     RAL: '6005'},
    { id: 4,  title: 'Светло-зеленый',     rgb: '#007641', bg_rgb: null,      ORACAL: '068',     RAL: '6029'},
    { id: 5,  title: 'Коричневый',         rgb: '#56351C', bg_rgb: null,      ORACAL: '800',     RAL: '8017'},
    { id: 6,  title: 'Красный',            rgb: '#B42024', bg_rgb: null,      ORACAL: '031',     RAL: '3000'},
    { id: 7,  title: 'Бордовый',           rgb: '#781214', bg_rgb: null,      ORACAL: '312',     RAL: '3005'},
    { id: 8,  title: 'Черный',             rgb: '#070809', bg_rgb: null,      ORACAL: '070',     RAL: '9005'},
    { id: 9,  title: 'Серый',              rgb: '#4A4C4C', bg_rgb: null,      ORACAL: '073',     RAL: '7043'},
    { id: 10, title: 'Коричневый/бежевый', rgb: '#56351C', bg_rgb: '#EAD294', ORACAL: '800/023', RAL: '8017/1014'},
];

const MAIN_DOMAIN_CITY = 'Москва'

const CITIES = {
    arh: 'Архангельск',
    astrahan: 'Астрахань',
    barnaul: 'Барнаул',
    belgorod: 'Белгород',
    bryansk: 'Брянск',
    cheboksary: 'Чебоксары',
    chel: 'Челябинск',
    chelny: 'Набережные Челны',
    cherepovets: 'Череповец',
    chita: 'Чита',
    ekb: 'Екатеринбург',
    grozny: 'Грозный',
    irkutsk: 'Иркутск',
    ivanovo: 'Иваново',
//---
    izhevsk: 'Ижевск',
    kaluga: 'Калуга',
    kazan: 'Казань',
    kemerovo: 'Кемерово',
    khabarovsk: 'Хабаровск',
    kirov: 'Киров',
    kostroma: 'Кострома',
    krasnodar: 'Краснодар',
    krasnoyarsk: 'Красноярск',
    kurgan: 'Курган',
    kursk: 'Курск',
    lipetsk: 'Липецк',
    magnitogorsk: 'Магнитогорск',
    mahachkala: 'Махачкала',
    murmansk: 'Мурманск',
//---
    nalchik: 'Нальчик',
    nn: 'Нижний Новгород',
    novokuznetsk: 'Новокузнецк',
    novorossiysk: 'Новороссийск',
    nsk: 'Новосибирск',
    ola: 'Йошкар-Ола',
    omsk: 'Омск',
    orel: 'Орёл',
    orenburg: 'Оренбург',
    oskol: 'Старый Оскол',
    penza: 'Пенза',
    perm: 'Пермь',
    petrozavodsk: 'Петрозаводск',
    pskov: 'Псков',
    rostov: 'Ростов-на-Дону',
//---
    ryazan: 'Рязань',
    rybinsk: 'Рыбинск',
    samara: 'Самара',
    saransk: 'Саранск',
    saratov: 'Саратов',
    sevastopol: 'Севастополь',
    shahty: 'Шахты',
    simferopol: 'Симферополь',
    skt: 'Сыктывкар',
    smolensk: 'Смоленск',
    sochi: 'Сочи',
    spb: 'Санкт-Петербург',
    stavropol: 'Ставрополь',
    sterlitamak: 'Стерлитамак',
    surgut: 'Сургут',
//---
    taganrog: 'Таганрог',
    tagil: 'Нижний Тагил',
    tambov: 'Тамбов',
    tlt: 'Тольятти',
    tomsk: 'Томск',
//---
    tula: 'Тула',
    tver: 'Тверь',
    tyumen: 'Тюмень',
    ufa: 'Уфа',
    ulanude: 'Улан-Удэ',
    ulyanovsk: 'Ульяновск',
    vladikavkaz: 'Владикавказ',
    vladimir: 'Владимир',
    vladivostok: 'Владивосток',
    volgograd: 'Волгоград',
    vologda: 'Вологда',
    volzhskiy: 'Волжский',
    voronezh: 'Воронеж',
    yalta: 'Ялта',
    yakutsk: 'Якутск',
    yaroslavl: 'Ярославль',
}

module.exports = {
    ROLES,
    CLASSES,
    STREETSIGN_COLORS,
    MAIN_DOMAIN_CITY,
    CITIES,
}
